version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DB_USER: root
          DB_NAME: circle_test
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libpq-dev
      - run: tox
